### ISSUE TITLE
Using double linked list goodly like

### ISSUE THREAD

**Issue by vishnukey** [JordanCarr/BigBucksRevisited#1]
tester:46 `if(iter.next().balance > iter.previous().balance)`

`iter.next()` moves the list cursor ahead by one, and `iter.previous()` moves it back by one, effectively not moving the cursor at all. trying comparing `iter.next()`.balance to `maxBalance`.

**Comment by JordanCarr** [comment]
http://img07.deviantart.net/c126/i/2015/112/9/6/facedesk_by_supremeoverl0rd-d5wfksf.png
